### ISSUE TITLE
Lighthouse Accessibility: Ensure ids are unique

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-hugo-themes#1038]
*Lighthouse flagged our pages as having duplicate ids, leading to invalid aria entries (specifically [aria-controls](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls))*.

### Steps to Reproduce

1. Visit https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/
2. Run Lighthouse in chrome dev console. It should flag some duplicate ids, e.g., `#nav-container_cc74bf5b-1a22-399e-2712-70abfff469d7`. You can find the corresponding elements with document.querySelectorAll('#nav-container_cc74bf5b-1a22-399e-2712-70abfff469d7')

**Expected:** 0 or 1 elements with id
**Actual:** 2 elements with this id

### Notes
There are probably others. Would be good to fix them all as part of this issue, or at least discover the scope.

**Comment by MAbdurrehman12** [comment]
Looks like there are more duplicate IDs. Most of them are from `nav_item.html` because both, `mobile_course_nav.html` and `desktop_nav.html` partials are being used in `home.html` and both of them are using the same `nav_item.html` partial with the same IDs hence duplication occurs. 

Currently, I'm looking into a few more things, will fix them and create the PR afterwards.

ps: running this JS snippet in the console points out all the duplicate IDs:
```
(function findDuplicateIds() {
    const ids = {};
    const all = document.all || document.getElementsByTagName("*");
    const elements_count = all.length;
    let total_duplicates = 0;
    for (let i = 0; i < elements_count; i++) {
        const id = all[i].id;
        if (id) {
            if (ids[id]) {
                console.log("Duplicate id: #" + id);
                total_duplicates++;
            } else {
                ids[id] = 1;
            }
        }
    }
    console.log("Total Duplicate IDs count: "+ total_duplicates);
})();
```  

<img width="387" alt="image" src="https://user-images.githubusercontent.com/93309234/217243489-18efe0e0-0c69-4329-a828-dd3a70bdc2ce.png">
