### ISSUE TITLE
Search: clicking the Resource link while already selected unselects it

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-hugo-themes#105]
### Steps to Reproduce

Go to `/search` and click "Resources". It should switch to resource search. Click that link again and it will switch to courses.

**Comment by Wassaf-Shahzad** [comment]
@pdpinch @gumaerc 
So I have done a bit of RnD on this issue and this is not as straight forward as it seems.

The thing is that this is working as designed. If we take a look at the code . It was written to `toggle`  the active search  type `on or off`. So we are not selecting between course or resource type , we are just toggling `resource type` `on or off` since we always default to `course type`.  If the resource type is already selected it and you click it again it just  toggles it off and we default back to course type.This can also lead to the search freaking out and giving resourceFiles as results while course type is selected 
<img width="1349" alt="Screenshot 2022-02-11 at 6 58 43 PM" src="https://user-images.githubusercontent.com/87968618/153606221-e05ba8ec-09c0-4f20-8d56-c0659c98600a.png">
This also has another side affect where if you filter courses and click the course type selector again it resets you filter results

**Comment by pdpinch** [comment]
I don't think "toggle" was the right UI metaphor for this case. They are more like tabs. 

What are our options for fixing this?
