### ISSUE TITLE
Video Gallery Resource Links in Offline Theme Not Working Properly

### ISSUE THREAD

**Issue by pt2302** [mitodl/ocw-hugo-themes#1063]
### Steps to Reproduce

1. Download a course ZIP file, for example at https://ocw.mit.edu/courses/9-40-introduction-to-neural-computation-spring-2018/download/. 
2. Decompress the ZIP file, open `index.html` in a browser, and click on `Lecture Videos`. 
3. Click on any video, for example "2. RC Circuit and Nernst Potential" 

### Expected Behavior

- The browser navigates to the `index.html` page for that video.

### Actual Behavior

- The browser displays a directory listing of the folder for that video resource.

**Comment by Wassaf-Shahzad** [comment]
@pt2302 @gumaerc I looked into this and although I was unable to get the offline theme running, I did figure out the issue. In **video-gallery-item.html** uses RelPermalink and not resource_url partial which I believe is causing the issue in cases of offline courses.
Since in offline theme resource_url was updated to point towards the index.html of static resources

```
<a class="video-link" href="{{- .RelPermalink -}}">
```

**Comment by pdpinch** [comment]
@Wassaf-Shahzad are you able to work on this, or should let someone else work on it?

**Comment by gumaerc** [comment]
@Wassaf-Shahzad To test the offline build locally with one course, the easiest way is to run the following in your `ocw-hugo-themes` directory, replacing my paths with your own:

`yarn build ~/Code/mitocwcontent/9.40-spring-2018 ~/Code/ocw-hugo-projects/ocw-course-v2/config-offline.yaml`

The resulting offline build will show up in the `dist` folder under your course content repo, in my case that would be `~/Code/mitocwcontent/9.40-spring-2018`. You were close in assuming that this URL needs to be generated through a partial, although the correct partial would be `page_url.html`, since this URL is supposed to be pointing to the video resource page with the embedded player in it, not the direct resource itself. The `resource_url.html` partial is for links directly to resources, such as the download links to download resources directly on the individual resource pages.

@pdpinch I put up a PR to fix this here: https://github.com/mitodl/ocw-hugo-themes/pull/1084

**Comment by gumaerc** [comment]
@pdpinch I just downloaded the ZIP file without republishing, and the links on the Video Lectures page seem to be working properly for me. Can you double check that you didn't open an old ZIP file or something and try again?

**Comment by pdpinch** [comment]
Sorry, slightly different bug that deserves its own issue:

https://github.com/mitodl/ocw-hugo-themes/issues/1095

The links on the local copy of `download/index.html` need a file name.
