### ISSUE TITLE
Use YouTube player controls when playing back a YouTube video

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#1103]
We should use the standard YouTube video controls when playing back YouTube videos. 

See https://github.com/mitodl/hq/discussions/418 for a full discussion of the reasoning behind this decision. 

#### Designs and Mockups

Switching to the YouTube controls means that we have to move the download button outside of the video player

See these InVision designs for the new location and behavior:
- https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347461/preview
- https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/472347462/preview

#### Acceptance Criteria:

- [x] When a video is streamed from YouTube, use the YouTube controller (note: all our videos stream from YouTube at this time) 
- [x] While it is rare, it is possible for a video to have no interactive captions. In that case, the "Transcript" button should not be displayed, but the download button should still be available. 
- [x] remove the extra space to the left of the interactive transcript, so it left aligns with the video player (see [InVision Comment](https://projects.invisionapp.com/d/#/console/21537330/472347462/comments/150602733))
- [ ] YouTube controller and the design changes should also work for embedded videos (eg., see this [embedded video page](https://ocw.mit.edu/courses/res-18-009-learn-differential-equations-up-close-with-gilbert-strang-and-cleve-moler-fall-2015/pages/video-series-overview/))

#### Related issues

- Switching to the YouTube controller should also close #978

**Comment by ibrahimjaved12** [comment]
I read up the discussions on this and saw the InVision screenshots. So I'm just confirming the design changes we have to do and their effects:

1. Replace current videoJS controller with YouTube controller for online version. For offline version, we may need to use a custom videojs player in future.
2. Use youtube controller's features --> the youtube captions button to display captions, **however** also display videojs' transcripts underneath the video (with the current line highlighted).
3. Move the download button to the Transcript bar underneath; the bar should still be there even when we have no interactive captions -- just without the Transcript text -- for the purpose of download.
4. The extra space to the left of the interactive transcript to be removed
 
Keeping (1) in account, I'm only making slight modifications wherever possible (and keeping the code for our current custom videoJS player mostly intact instead of entirely erasing it; in case for future we have to reutilize it for offline courses)

(2) This would mean disabling to display the track on screen for videoJS (otherwise we have two overlapping captions; one from YouTube, and one from videoJS). For proof of concept I did test and I was able to display ongoing transcripts underneath the video while having only YouTube's captions displayed (videoJS track captions disabled on video) -- i.e only having one caption at a time (no overlapping).

(3) I believe our current download icon functionality is tied to custom videoJS controller. I was able to get the download icon at exactly the location mentioned in the InVision screenshots using CSS; but as soon as I switched controller to YouTube the button disappeared. Either way, I believe a new implementation for the download icon button should be better as opposed to using current implementation for the download popup. If In case in future we have to remove the current customisations of videoJS controller; or, have to modify it for offline courses -- so in those cases, our youtube controller implementation remains unaffected.

Also,
I want to ask: It appears that our current styling is a little bit different from the InVision screenshots.
These changes:
a) Transcript, Related Resources text on bars is uppercase
b) The styling for the transcripts container
Are these to be followed right now?

This is what I currently have without the download icon after exploring a bit:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/109785089/226894382-9eb4d476-19a9-424e-835e-68ebca768d33.png">
The keyboard shortcuts are also working fine as expected.

**Comment by ibrahimjaved12** [comment]
Thanks @pdpinch . I'm currently working on the InVision styling changes on the `.video-tab` and transcript container as the current styling for these segments will have to be mostly replaced with the new styling. I'll up a draft PR on Monday.

**Comment by ChristopherChudzicki** [comment]
@ibrahimjaved12 Your changes look nice! I was looking at the keyboard issue. My understanding right now is that we currently load the iframe inside VideoJS's player, and VIdeoJS displays a "poster" over the iframe before it plays. Users click the poster, and that plays the video (via Youtube API, which uses [Window.message events](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) to communicate with the iframe. But then the iframe document is not focused, so the youtube keyboard controls do not work.

As far as I know, we can't manually focus the iframe document on our side. *(We can focus the iframe, but not whatever element inside the iframe needs to be focused for youtube's controls to work.)*.

IMO, our best bet is to disable the VideoJS poster. Youtube will display a poster image itself:

<img width="796" alt="Screenshot 2023-03-29 at 9 42 06 AM" src="https://user-images.githubusercontent.com/9010790/228557198-be577db6-1285-4613-89f3-1975bfc66a8c.png">

### Note
The "Watch on Youtube" thing is present on localhost, I believe it is NOT present on actual OCW site. (Try embedding the iframe code via dev console.). I have observed that YouTube embeds behave slightly differently on `.edu` and non-`.edu` sites.

**Comment by ibrahimjaved12** [comment]
> @ibrahimjaved12 Your changes look nice! I was looking at the keyboard issue. My understanding right now is that we currently load the iframe inside VideoJS's player, and VIdeoJS displays a "poster" over the iframe before it plays. Users click the poster, and that plays the video (via Youtube API, which uses [Window.message events](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) to communicate with the iframe. But then the iframe document is not focused, so the youtube keyboard controls do not work.
> 
> As far as I know, we can't manually focus the iframe document on our side. _(We can focus the iframe, but not whatever element inside the iframe needs to be focused for youtube's controls to work.)_.
> 
> IMO, our best bet is to disable the VideoJS poster. Youtube will display a poster image itself:
> 
> <img alt="Screenshot 2023-03-29 at 9 42 06 AM" width="796" src="https://user-images.githubusercontent.com/9010790/228557198-be577db6-1285-4613-89f3-1975bfc66a8c.png">
> 
> ### Note
> The "Watch on Youtube" thing is present on localhost, I believe it is NOT present on actual OCW site. (Try embedding the iframe code via dev console.). I have observed that YouTube embeds behave slightly differently on `.edu` and non-`.edu` sites.

Thanks for the explanation @ChristopherChudzicki. You're right -- and disabling the videoJs poster did indeed do the trick.
And thanks for the note. I'll check that out. I guess it is similar to the "related videos" manner that we previously had. On localhost, when we paused a video, it was different, and different for the .edu site.

**Comment by ibrahimjaved12** [comment]
I'm reopening this issue for Embed video resources.
Also @pdpinch I'm updating the acceptance criteria to reflect this.

Sorry, I wasn’t aware that there are any different kinds of video (embed videos) apart from regular videos. It wasn’t mentioned in the issue, and I also didn’t know that there are such kinds of courses with embed videos. That's how this got missed. The link you gave earlier for embed video, was of regular video page. Otherwise our testing process did involve all kinds of courses with different video tabs -- that we knew of.

The current implementation does have YouTube controller in embed video player, but the download link is missing. So I'm reopening this issue for that.

I have some questions for this.

These are the two links for embed videos you gave me on Slack:
1. [https://ocw.mit.edu/courses/res-18-009-learn-differential-equations-up-close-with-[…]t-strang-and-cleve-moler-fall-2015/pages/video-series-overview/](https://ocw.mit.edu/courses/res-18-009-learn-differential-equations-up-close-with-gilbert-strang-and-cleve-moler-fall-2015/pages/video-series-overview/)
2. https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/resources/clip-linear-systems-and-planes/

I don't think the 2nd link is embed video link. Can you please confirm this. From what I saw in the code, the embed video should have `div` class of `video-embed`, and in the code I saw that it should not have transcript (or any video tab for that reason - related resources, lecture notes, etc). Both are true for 1st link, but neither for the 2nd link. 
(If the current implementation changes are not appearing, try clearing your cache - that should do the trick)

Also, for comparison, this is how embed video page looked previously:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/109785089/230320873-cf36c40e-faa6-486c-b967-d3197680d3f1.png">

And this is how it currently looks:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/109785089/230311544-a132fcc4-07d7-4050-a22b-17f7d9ccc152.png">
(Download video button is missing)

And when we click on "view video page", it opens as a regular video resource (with download button as well):
<img width="855" alt="image" src="https://user-images.githubusercontent.com/109785089/230312641-106d0069-5589-41e1-a23e-5e092540e848.png">

I tweaked some stuff in dev console, and this is how embed video page would look.
a)
<img width="871" alt="image" src="https://user-images.githubusercontent.com/109785089/230330206-8d586ed4-b36a-4133-b287-4477804f2235.png">

vs
b)
With extra padding on bottom (observe where the download video button is)
<img width="858" alt="image" src="https://user-images.githubusercontent.com/109785089/230330355-f0fa6822-d00e-4339-9d85-f28d6e1f868e.png">

**which one of these is more suitable from a) and b) (with or without extra bottom padding)**
<img width="849" alt="image" src="https://user-images.githubusercontent.com/109785089/230330888-a828ac0e-8bd3-4cde-804d-b671426726f0.png">

**Also, another question:**
The old implementation:
a) Does not have video tab in its implementation (eg. for transcript, related resources, lecture notes) for embed videos.
b) It also does not have "Download transcript" button, even when there is transcript available to be downloaded (if we click on "view video page" on embed video, and then it opens as a regular video resource; then the button for "download transcript" appears, otherwise there is only "download video". [Picture 1 for old player, embed video reference](https://user-images.githubusercontent.com/109785089/230320873-cf36c40e-faa6-486c-b967-d3197680d3f1.png),[ Picture 2 for old player, inside "view page" of embed video reference -- to show that download transcript button does exist for that video](https://user-images.githubusercontent.com/109785089/230330888-a828ac0e-8bd3-4cde-804d-b671426726f0.png))

I think it should at least have a "download transcript" button along with "download video" on the embed video page (if transcript is available for download)?

The new implementation will have one video tab for download button (as shown in screenshots above in this message), but what about these other changes. Please let me know which ones to keep and which ones to change for embed videos.

**Comment by pdpinch** [comment]
Sorry about this oversite @ibrahimjaved12. I should have mentioned it in the issue. 

You are correct. This is an embedded video player: 
https://ocw.mit.edu/courses/res-18-009-learn-differential-equations-up-close-with-gilbert-strang-and-cleve-moler-fall-2015/pages/video-series-overview/
    
And this is a single video page player:
https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/resources/clip-linear-systems-and-planes/
The single video player on this page has [a bug, which I opened separately](https://github.com/mitodl/hq/issues/1196).

For the design of the embedded video player, is it possible to put the download button in the same line with the line to "View Video Page" ?

> I think it should at least have a "download transcript" button along with "download video" on the embed video page (if transcript is available for download)?

I agree. You should be able to download the transcript. 

The other "tabs" (e.g. related resources, interactive transcript, etc.) are omitted on purpose so as to avoid cluttering up the page too much.

**Comment by ibrahimjaved12** [comment]
@pdpinch 
> For the design of the embedded video player, is it possible to put the download button in the same line with the line to "View Video Page" ?

Yes. I tried tweaking it in dev console, and I got something like:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/109785089/230586151-f2d92815-d159-471c-8bbf-4b4c91bf2fbf.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/109785089/230586199-db91b81d-a6a8-423e-b60c-ba1ac8b5e3ce.png">
This is just a rough sketch. It could be something like, the grey area would expand only when the download button is clicked.
But either way, imho, I think the previous one with a bar is suiting better, and it would be uniform/consistent also.

But it could also look better in the same line with "view video page" as well, and I can see where you're coming from with this idea. But I think if we knew better what layout aesthetics would suit for this page in this setting that would be best.

I have a suggestion that is, we can implement the previous, [this design](https://user-images.githubusercontent.com/109785089/230330355-f0fa6822-d00e-4339-9d85-f28d6e1f868e.png) currently until we get an updated design from the UI/UX team so this can go to the production with a download link instead of being on hold.
And when we get updated design, we can work on this again with the new layout.

But if we do have some ideas for the design for this page, then we could get on this right now. Do you have anything in mind regarding this?

> The other "tabs" (e.g. related resources, interactive transcript, etc.) are omitted on purpose so as to avoid cluttering up the page too much.

Makes sense
