### ISSUE TITLE
infinite scroll doesn't display all results

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#114]
### Steps to Reproduce

Visit https://ocwnext.odl.mit.edu/search/?q=%22quantum+mechanics%22 and continuously scroll to the bottom.  Open an inspector and compare the last `article` element's `aria-labelledby` property to the total amonut of results listed at the top of the page

### Expected Behavior

The page renders all of the results that are supposed to be returned by the search terms

### Actual Behavior

An inconsistent amount of search results are actually rendered

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/12089658/122275703-00ed8a00-ceb2-11eb-8eb2-851f0ac53063.png)

**Comment by aliceriot** [comment]
I think I may see the root cause of the issue. I'll try a little experiment and open a bugfix PR if my hunch is correct.

**Comment by aliceriot** [comment]
yup! got search working locally against the RC cluster. Confirmed my suspicion. root cause is here:

https://github.com/mitodl/ocw-hugo-themes/blob/main/www/assets/js/components/SearchPage.js#L77

when the `runSearch` callback is called multiple times, and then multiple requests are in-flight at the same time, each separate call of the callback will have it's own copy of the `results` prop. Then when they all come back in, each will call `setResults` with it's own copy of `results` and then whatever came back from the backend for its own, particular API call. This will mean that although many API calls are made in a burst, actually in practice only the final one will update the state because the additions made by all the previous ones will be overwritten.

The way to fix this is by passing a callback in to the `useResults` call. See [this page](https://reactjs.org/docs/hooks-reference.html#functional-updates) in the React docs for how this works. Basically, if I declare some state

```ts
const [mystate, setMystate] = useState([])
```

if I then call `setMystate` with a callback, like this:

```ts
setMystate(cur => [...cur, newItem])
```

I get a guarantee from React that the value `cur` with which my callback is called will always be up-to-date. So I can pass the `setMystate` callback around wherever I want, and I don't need to worry about ensuring that the value I pass in is the latest one.

Anyhow, by making this change:

```diff
diff --git a/www/assets/js/components/SearchPage.js b/www/assets/js/components/SearchPage.js
index 798d091..6821c69 100644
--- a/www/assets/js/components/SearchPage.js
+++ b/www/assets/js/components/SearchPage.js
@@ -75,16 +75,17 @@ export default function SearchPage() {
       setSearchFacets(new Map(Object.entries(newResults.aggregations ?? {})))
 
       setSearchResults(
-        from === 0 ?
+        results => (
+          from === 0 ?
           newResults.hits.hits :
           [...results, ...newResults.hits.hits]
+        )
       )
       setTotal(newResults.hits.total)
       setCompletedInitialLoad(true)
     },
     [
       setSearchResults,
-      results,
       setTotal,
       setCompletedInitialLoad,
       setSuggestions,
```

the race condition goes away:

![Screen Shot 2021-06-16 at 4 52 41 PM](https://user-images.githubusercontent.com/6207644/122291925-66964200-cec3-11eb-8ce6-cbb907cd2660.png)
![Screen Shot 2021-06-16 at 4 53 24 PM](https://user-images.githubusercontent.com/6207644/122291936-69913280-cec3-11eb-94f0-942c2a843040.png)

and so even though the not-so-great issue of it firing off like 5-6 requests instead of just one is still there, we do get all of the data to be added to the state and whatnot.

I haven't investigated if this messes up the ordered of them yet - it may if the requests don't come back in their requested order. I'll figure that out and fix it if so and then open a bugfix PR tomorrow.

**Comment by aliceriot** [comment]
So fixing the issue by removing the update race condition does mean that there is still a data race where search requests will still update the visible results in the order they come back, not in the order that they are issued. This means that scrolling down on the same search will produce a different result order each time.

So I went ahead and also made a fix so that only one request is made at a time. I think in ocw-hugo-themes we weren't passing one of the props into `useCourseSearch` properly, so I just fixed that and now it only makes one request at a time, fixing the issue of not showing all results and also reducing this burstiness of making a whole bunch of requests against the backend at once.
