### ISSUE TITLE
Upgrade hugo-bin-extended to 0.112.7

### ISSUE THREAD

**Issue by HussainTaj-arbisoft** [mitodl/ocw-hugo-themes#1161]
### Background / Purpose

We will upgrade [ocw-course-publisher](https://hub.docker.com/r/mitodl/ocw-course-publisher) to `0.6` Hugo 0.112.7 (refer to https://github.com/mitodl/ocw-studio/issues/1821), we also need to update [hugo-bin-extended](https://www.npmjs.com/package/hugo-bin-extended) to 0.112.7 to match the version in Studio.

### Description

Update [hugo-bin-extended](https://www.npmjs.com/package/hugo-bin-extended) to 0.112.7 to match the version in Studio. This should be done in conjunction with or after https://github.com/mitodl/ocw-studio/issues/1821.

### Acceptance Criteria

- [ ] Hugo is upgraded to 0.112.7
- [ ] Dev environment works correctly

**Comment by ChristopherChudzicki** [comment]
**Suggestion:** IMO, we should at least open the PR to upgrade `hugo-bin-extended` BEFORE doing the other work (studio PR, ocw-hugo-publisher update). Because:
- updating hugo in `ocw-hugo-themes` is **very** low effort. *We can open the PR, and wait to merge it.*
- our e2e tests will run

For example, the issue @gumaerc caught in https://github.com/mitodl/ocw-studio/pull/1826 could (in principle) have been caught by a Playwright test in ocw-hugo-themes. It would not actually have been caught unless we do:
- #1166

**Comment by gumaerc** [comment]
> For example, the issue @gumaerc caught in https://github.com/mitodl/ocw-studio/pull/1826 could (in principle) have been caught by a Playwright test in ocw-hugo-themes.

I'm not so sure this would be the case, as the issue only happens when using a `baseURL` setting with a subfolder prefix. All our tests assume that the root of the site is `/`. We would have to add tests that run Hugo this way, and at that point IMO we are testing functionality that should be tested by Hugo itself. Not that it would be bad to test expected output when using `baseURL`, but I do think this is somewhat of a special case where a bug was introduced into Hugo itself and had nothing to do with our theme.

**Comment by ChristopherChudzicki** [comment]
> All our tests assume that the root of the site is `/`

This is not accurate for our e2e tests:

```
Now serving the following sites:
┌────────────────────┬──────────────────────────────────────────────────┐
│ Site               │ URL                                              │
├────────────────────┼──────────────────────────────────────────────────┤
│ ocw-ci-test-course │ http://localhost:3010/courses/ocw-ci-test-course │
├────────────────────┼──────────────────────────────────────────────────┤
│ ocw-ci-test-www    │ http://localhost:3010/                           │
└────────────────────┴──────────────────────────────────────────────────┘
```

Roughly, the e2e tests:
1. Build several hugo site (`hugo`, not `hugo serve`) to a directory:
    ```
    tmp
    |-- courses/
        |-- ocw-ci-test-course
        |-- ... *other potential courses could be added*
    |-- ocw-ci-test-www
    ```
2. Serve the `tmp/` directory with a static file server **and** redirect requests not beginning with "courses" to `ocw-ci-test-www`.
```

**Comment by gumaerc** [comment]
Whoops, I edited my comment above after I realized my error, but for posterity I did make a comment assuming that we don't test with an explicit `baseURL`.

**Comment by HussainTaj-arbisoft** [comment]
> ... we should at least open the PR to upgrade hugo-bin-extended BEFORE doing the other work

This makes sense to me. Thank you for the suggestion.

> ... we should use syntax like "hugo-bin-extended": "~0.112.0",

@gumaerc could setting `"hugo-bin-extended": "~0.112.0"` cause any inconsistent behavior between Studio and local builds? I'm inclined to keep the version pinned to exactly match the Studio's Hugo version. It should avoid a scenario like "It works on my machine but not the server, I don't know why." Although, I don't know how likely that scenario is in our project.

Since I was going to work on the publisher image today, I'll follow @ChristopherChudzicki's suggestion and test 0.112.7 on themes first and put up a draft PR.
