### ISSUE TITLE
Resource link on a line by itself does not render with a line break. 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#302]
### Steps to Reproduce

1. Create a page in studio with multiple resources on separate lines, like https://ocw-studio-rc.odl.mit.edu/sites/peters-test-2021-09-29-1/type/page/

<img width="805" alt="image" src="https://user-images.githubusercontent.com/430126/146078601-c25faca7-c1d3-4b89-864a-3c26e1f11acf.png">

2. Publish it. This will create three resource short codes, each on their own line, like https://github.mit.edu/ocw-content-rc/pinch-test-2021-09-29-01/blob/main/content/pages/resource-links-line-breaks.md

<img width="822" alt="image" src="https://user-images.githubusercontent.com/430126/146078620-06832925-63fd-4fe4-ac4f-d4207803e17b.png">

3. Examine the published output. The three links are run together on one line: https://ocw-draft-qa.global.ssl.fastly.net/courses/peters-test-2021-09-29-1/pages/resource-links-line-breaks/

<img width="555" alt="image" src="https://user-images.githubusercontent.com/430126/146078698-b8fd4c8c-0e6b-40f6-b3e5-67383396d9e0.png">

### Expected Behavior

The published output should look more like the WYSIWYG editor, with line breaks between each source code. 

### Actual Behavior

It seems like the short code somehow swallows the `\n` between each item.

**Comment by alicewriteswrongs** [comment]
This occurs because of the logic that Hugo uses to decide when content in Markdown should be wrapped in a `<p>` tag and when it should not. When shortcodes are on a line by themselves, without any other text content, Hugo assumes that they should not be wrapped in a `<p>` tag, which generally makes sense because shortcodes are often used to render block-level content (like iframes or the like) which shouldn't be inserted into a paragraph or otherwise treated like text.

In our case, however, our `resource_link` shortcode renders an anchor tag, which can be treated like inline (non-block) content just fine. But I think from Hugo's perspective our use-case is an edge-case / exception. From my research on the Hugo forums and issues and so on there is not, currently, a way to tell Hugo that the rendered content of a shortcode should be treated as inline (text) content in this case.

A workaround would be to tell content authors that if they want something like this, then the best way to do it is to use a list, which will be properly formatted as they expect.

**Comment by pdpinch** [comment]
@gumaerc is addressing this with #485

**Comment by pdpinch** [comment]
@gumaerc you merged #485. I think this can be closed?

**Comment by gumaerc** [comment]
@pdpinch Yep, closing.
