### ISSUE TITLE
CHP image caption has expand widget even when all text is visible 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#396]
### Steps to Reproduce

1. navigate to https://ocw-published.odl.mit.edu/courses/1-017-computing-and-data-analysis-for-environmental-applications-fall-2003/ (in Firefox) or https://ocwnext-rc.odl.mit.edu/courses/1-017-computing-and-data-analysis-for-environmental-applications-fall-2003/

### Expected Behavior

- no expand widget, because the entire caption fits in the available area

### Actual Behavior

- there is an expand widget. Clicking on it expands the box, but doesn't reveal any more text.

### Screenshot or Screencast

<img width="331" alt="image" src="https://user-images.githubusercontent.com/430126/151806646-ffd341dc-81e9-466c-ad86-e97d08ac572f.png">

**Comment by MAbdurrehman12** [comment]
This issue is resolved [here](https://ocwnext-rc.odl.mit.edu/courses/1-017-computing-and-data-analysis-for-environmental-applications-fall-2003/) but since the content can have HTML elements which are counted in hugo `len` function but not shown to the user, so it is possible that this issue occurs for any course.
This can be resolved, later on, by a custom JS solution as discussed [here](https://github.com/mitodl/ocw-hugo-themes/pull/407)
