### ISSUE TITLE
render links in image captions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#432]
See https://ocwnext.odl.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/

<img width="334" alt="image" src="https://user-images.githubusercontent.com/430126/153497598-bea25731-532a-4885-b7be-2fcac7b10b00.png">

**Comment by pdpinch** [comment]
@ChristopherChudzicki will your work in https://github.com/mitodl/ocw-studio/pull/1002 will address this particular case?

**Comment by gumaerc** [comment]
There is currently no way to render shortcodes that are stored anywhere except the markdown body of a markdown file.  Since `caption` is stored in the front matter of video pages, shortcodes will indeed not function.  It's the same issue we had rendering shortcodes in the course description.  There are two two functions within Hugo that will render markdown manually in a template, [`markdownify`](https://gohugo.io/functions/markdownify/) and [`.RenderString`](https://gohugo.io/functions/renderstring/).  Neither of these support rendering shortcodes.  There is a [feature request](https://github.com/gohugoio/hugo/issues/6703) in the Hugo Github that I've commented on pretty extensively that's been up for about 2 years now.  I believe it's on their radar of things to do, but keeps getting pushed from milestone to milestone and I'm unsure of when (if ever) it will be implemented.  So, even if we replaced `baseurl` with a different shortcode, we would have the same issue.  Our only options are messy and involve writing in raw, static URLs:

 - Write in relative URLs based on where the page linking to the video is in relation to the course root (and subsequently the resources folder)
 - Write in a raw root-relative URL including the course prefix

Neither of these options are great, as the first option would add complexity to the markdown publishing process, likely requiring some custom logic during serialization.  The second option would cause confusion during local development as all the URLs would be prefixed with the course.  These are reasons why the shortcode approach, especially with `resource_file` in our case, is especially good.  It keeps the intended URL separate from the build context.  Unfortunately in this case though, we might have to use a different solution.

**Comment by MAbdurrehman12** [comment]
@gumaerc Thanks for the explanation!
It looks like there are quite a lot of pending issues in their repo.

What if we remove the `baseurl` shortcode from the image caption description and render links like in other captions? Don't they work as expected?

**Comment by pdpinch** [comment]
This is not worth the effort in this case. I'll ask the OCW team to reauthor this caption.
