### ISSUE TITLE
oversized "buy at mitpress" logo

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#477]
### Steps to Reproduce

See https://ocwnext-rc.odl.mit.edu/courses/21m-380-music-and-technology-sound-design-spring-2016/pages/instructor-insights/engaging-deeply-in-the-design-process/

### Screenshot or Screencast

<img width="1695" alt="image" src="https://user-images.githubusercontent.com/430126/155615426-f0788b8f-727f-4d57-bcfb-5e741be121db.png">

**Comment by MAbdurrehman12** [comment]
All the images in instructor insights were scaled in this [PR](https://github.com/mitodl/ocw-hugo-themes/issues/65) and this is a side-effect of that. In order to fix this, I guess we should have a criteria, which images to scale and which images to not scale. 
Not sure what that criteria should be, as the content is completely dynamic.

**Comment by pdpinch** [comment]
@gumaerc or @alicewriteswrongs can you advise on this?

**Comment by gumaerc** [comment]
@MAbdurrehman12 wasn't the original issue here only supposed to scale images inside of table cells?  Why don't we just narrow the scope?

**Comment by MAbdurrehman12** [comment]
@gumaerc I don't remember exactly but I think this [PR](https://github.com/mitodl/ocw-hugo-themes/pull/388) was created to scale the images in instructor insights only and they were not limited to table cells. However, the images in table cells got too small (because table cell's 100% width was also applied to them), so in order to fix that, this [PR](https://github.com/mitodl/ocw-hugo-themes/pull/470) was created.

**Comment by pdpinch** [comment]
This has been fixed by #528
