### ISSUE TITLE
H3 sizing inconsistent

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#632]
### Steps to Reproduce

- On https://ocwnext.odl.mit.edu/courses/6-004-computation-structures-spring-2017/pages/instructor-insights/ the H3 is computed to 24px
- On https://ocwnext.odl.mit.edu/courses/24-912-black-matters-introduction-to-black-studies-spring-2017/pages/instructor-insights/ the H3 is computed to 16px 

### Expected Behavior

H3 should be the same size everwhere (not just instructor insights pages) 

### Actual Behavior

There seems to be an style applied on the 2nd example: 
```
#course-content-section h3 {
  font-size: 1rem !important;
}
```

### Related Issues

- #633

**Comment by Wassaf-Shahzad** [comment]
@pdpinch I did some RnD on this and the reason those h3s have a custom font-size is because those set of h3 are generated by hugo and we can't replace them with h4s unless we change it in ocw-studio and I think in ocw-to-hugo as well for legacy courses, Since these are generated from .md files. So we had to override the font-size in styles. I can remove the custom style but It will make those subheading a bit bigger if you like.

### Screenshots
With default h3 styles
<img width="1348" alt="Screenshot 2022-04-12 at 10 20 12 PM" src="https://user-images.githubusercontent.com/87968618/163018739-267b57e3-c822-4367-a655-d518c2f6a6e2.png">

With current overridden h3 styles
<img width="1348" alt="Screenshot 2022-04-12 at 10 20 18 PM" src="https://user-images.githubusercontent.com/87968618/163018904-3d8e7540-809f-4d65-a0cf-eb46fbc9ff32.png">

**Comment by pdpinch** [comment]
We are planning a site-wide CSS update. I'm going to put this on hold until that is ready, and we consider this at the same time.

**Comment by pdpinch** [comment]
Can we fix this in the courses-v2 theme?

**Comment by MAbdurrehman12** [comment]
@Wassaf-Shahzad Since this issue will be fixed by https://github.com/mitodl/ocw-hugo-themes/pull/794 so I'm assigning it to you
