### ISSUE TITLE
scale up the images in instructor insights

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#65]
For instructor images, scale them up to full column width.

#### Designs and Mockups

Before: 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/430126/119200468-fe3a7900-ba5a-11eb-9763-42fa2ed13dbf.png">

After:

<img width="472" alt="Screen Shot 2021-05-19 at 4 33 09 PM" src="https://user-images.githubusercontent.com/430126/119200427-e95de580-ba5a-11eb-99b0-eb7479a99b45.png">

#### Acceptance Criteria:

- [ ] this change should probably be limited to instructor insights

**Comment by MAbdurrehman12** [comment]
@pdpinch I have created a PR for this but I have few things in mind: 
- All images are scaled and since images have different sizes, so scaling relatively smaller images, to cover 100% width will cause distorted pixels. But if the images coming are of high quality then we are good!
  
- Since all the content is coming from `.md` files and content is being rendered like this: 
![image](https://user-images.githubusercontent.com/93309234/151173706-c46ee85e-929b-4424-92a8-a402075546b0.png) 
which is being reused for other sections as well and global css is applied to it so I'm not sure whether we can limit this change to `instructor insights` only. Perhaps, @gumaerc might have any suggestion?

**Comment by pdpinch** [comment]
In the Instructor Insights section, the images should all be high enough resolution for this to work. 

If this change affects _all_ images though, we might have some undesirable effects on:
1. video gallery pages like https://ocwnext.odl.mit.edu/courses/18-404j-theory-of-computation-fall-2020/video_galleries/video-lectures/
2. courses with tiny thumbnails like https://ocwnext-rc.odl.mit.edu/courses/9-00sc-introduction-to-psychology-fall-2011/pages/brain-ii/

**Comment by MAbdurrehman12** [comment]
Okay, I'll look into it

**Comment by MAbdurrehman12** [comment]
@pdpinch I have updated the PR and now this change (scaling images) is only applied to `Instructor insights` and the PR is ready for review. However, I'm still thinking that maybe this should a fix in studio, from where all the images are being generated/coming, as we **only** have to give `width:100%` to those images which we need to scale.
Perhaps, @gumaerc can share his thoughts?
