### ISSUE TITLE
Course lists aren't sorted according to studio order

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#705]
(I'm not sure if this is a bug in the way studio writes out course lists, or in the way the theme interprets the list) 

### Steps to Reproduce

1. Take a look at the order of courses in the list at https://ocw-studio.odl.mit.edu/sites/ocw-www/type/course-lists/edit/2b404bc3-dd20-4e8c-b4c2-bc70f9d4a838/
2. Note that the first course is "Fundamentals of Biology"
3. Take a look at the markdown in github: https://github.mit.edu/mitocwcontent/ocw-www/blame/main/content/course-lists/scholar-courses.md
4. Note that the first course is "Fundamentals of Biology"
5. Take a look at the rendered site: https://ocw.mit.edu/course-lists/scholar-courses/

### Expected Behavior

- The order on https://ocw.mit.edu/course-lists/scholar-courses/ should be the same as the order in studio

### Actual Behavior

- On https://ocw.mit.edu/course-lists/scholar-courses/ the list starts with "Principles of Microeconomics"

**Comment by MAbdurrehman12** [comment]
This issue seems to occur from [here](https://github.com/mitodl/ocw-hugo-themes/blob/ab90cfe81964a6ca7fc972b76e8fc87a4d1f6654/www/layouts/course-lists/single.html#L18) as I think on merging dicts in Hugo, order is not maintained, and then the order of this dis-ordered dict is again disturbed while iterating through it via `Object.entries` [here](https://github.com/mitodl/ocw-hugo-themes/blob/ab90cfe81964a6ca7fc972b76e8fc87a4d1f6654/www/assets/js/hooks/hugo_data.ts#L90). 

I spent some time figuring out a suitable solution/tweak but couldn't come up with anything. I think 1 solution can be to change the approach here from `nested objects` to array of objects, so we can replace `merge` with `append` or something else, as I think with arrays we can maintain the original order.

There might be some other solution that I can't think of at the moment so I wanted to have someone's thoughts on this before implementing it. 
Maybe @gumaerc or @mbertrand?
