### ISSUE TITLE
ocw-www resource pages don't publish 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#708]
### Steps to Reproduce

1. Add a resource to ocw-www, like https://ocw-studio-rc.odl.mit.edu/sites/ocw-www/type/resource/edit/65120dad-ad2a-41d8-98ac-54d9339b4468/
2. Add a link to it on a page, like https://ocw-studio-rc.odl.mit.edu/sites/ocw-www/type/page/edit/fabb4fde-a5ad-4013-962c-34e3273d183f/
3. publish to stage

### Expected Behavior

- the link should work
- there should be a resource page at https://ocw-draft-qa.global.ssl.fastly.net/resources/full-study-gender-roles-and-occupations-v2/

### Actual Behavior

- link is broken
- no resource pages at all

**Comment by MAbdurrehman12** [comment]
@pdpinch We don't have any `resources` layout in `themes/base-theme` or `themes/www`, though we have one in `themes/courses`. Due to this, we can load/serve `course` resources but cannot load `ocw-www` resources. 

So I think moving `resources layout`, along with several other `partials` which are being used in this layout, to `base-theme` will do the job!  But I wonder why it wasn't done in the first place? Maybe it wasn't required at that time or there was any other reason, not sure. If @gumaerc has any thoughts on this?

Another thing is that the `resources` URL is being redirected to `courses`.
e.g: `ocw.mit.edu/resources/resource-slug` redirects to `ocw.mit.edu/courses/resource-slug`

So the resource which you're trying to access here `fastly/resources/full-study-gender-roles-and-occupations-v2/` is being redirected to `fastly/courses/full-study-gender-roles-and-occupations-v2/` which will certainly throw `404`.

I'm not sure whether this has been done deliberately due to some reason or this is a bug at DevOps side, so even if we move the `resources` layout to `base-theme`, this redirection will still be an issue for `ocw-www` resources.

**Comment by pdpinch** [comment]
You are correct about the missing layout. Carey and I agree with the plan to move it from courses to the base theme.

As for the redirect, it only applies when the URL is a 404. Once we have the files in place, it won’t interfere.

**Comment by MAbdurrehman12** [comment]
Thanks for the update.
Did Carey start working on this or I can create its PR?
