### ISSUE TITLE
Next previous buttons not rendered

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#801]
### Steps to Reproduce

- Note: this issue seems to be on RC and local only. Not on prod
- Visit https://live-qa.ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/pages/biochemistry/macromolecules-lipids-carbohydrates-nucleic-acid/

### Expected Behavior

- Next and previous buttons should be rendered properly and clickable. Upon click, they should redirect us to the correct page. 

### Actual Behavior

- Buttons not rendered and plain text (including links) is displayed

### Screenshot or Screencast

<img width="653" alt="image" src="https://user-images.githubusercontent.com/93309234/180194042-d0e26981-5635-4e6a-ae7a-9329939daf85.png">

**Comment by Wassaf-Shahzad** [comment]
@pdpinch I looked into this issue an for some reason the macromolecules page is using `baseurl` shortcodes rather than using `resource_links`. I updated the shortcode and it fixed the issue.
<img width="1160" alt="Screenshot 2022-08-02 at 5 54 14 PM" src="https://user-images.githubusercontent.com/87968618/182382926-8557003d-7003-4902-b54e-49be4d03da50.png">
