### ISSUE TITLE
Navbar logo and course info drawer close icon missing in course v2

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/ocw-hugo-themes#817]
### Steps to Reproduce

- Visit any course on v2 course theme
    - Either by appending `course-v2` in in OCW QA URL. e.g: https://live-qa.ocw.mit.edu/course-v2/courses/wgs-s10-history-of-women-in-science-and-engineering-fall-2017/ 
    - or build any course on new theme locally (How to do it? Check the description of this [PR](https://github.com/mitodl/ocw-hugo-themes/pull/784#issue-1291571736))

### Expected Behavior

- All the static images should load/render fine (including logo in navabr and course info drawer close icon)

### Actual Behavior

- logo in navabr and course info drawer close icon don't load having 404 errors in console.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/93309234/183863375-8abc37d1-aba9-4e75-b448-dd6453894824.png">

### Screenshot or Screencast

<img width="267" alt="image" src="https://user-images.githubusercontent.com/93309234/183863473-cf037335-0f3d-4717-a3ef-7f63d1b1ba9e.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/93309234/183863510-2bd1bd29-c154-4f18-bc0f-38059e5ef142.png">

**Comment by gumaerc** [comment]
This should be fixed now.  The issue here was that the `ocw-www` build did not complete when the RC was created with the compact design PR merged in.  Assets in the `static` folder of any given theme are copied 1:1 to the output folder of the site you are building, so in order to refresh the `/images` folder at the root `ocw-www` needs to be rebuilt.
