### ISSUE TITLE
MathJax rendering fails on 6.004 S17

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#821]
### Steps to Reproduce

1. See https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/pages/c3/c3s1/
2. Find the text `\textrm` 

### Expected Behavior

- LaTeX code should render and not display as code
- rendered Mathjax should fit in central column 

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/184272747-8a093290-772a-4cb2-a290-e27a3770557c.png)

**Comment by pt2302** [comment]
@pdpinch @Wassaf-Shahzad It appears that this is caused by incorrectly delineating LaTeX in the code rather than a rendering error: the errors come up when the LaTeX is being wrapped in `\)[TeX]\(`  rather than `\([TeX]\)` - the parentheses are going in the wrong direction. Also, the top of this page shows styling information:

```
.toc { margin-left: 2em; } .lecslide { margin-top: 1em; margin-bottom: 1em; 
border-top: 0.5px solid #808080; padding-top: 1em; text-align: center; } 
.lecslideimg { width: 5in; border: 1px solid black; }
```

**Comment by pdpinch** [comment]
Thanks for the tip @pt2302. This has been fixed.
