### ISSUE TITLE
compact footer for course-v2 theme

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#861]
#### Designs and Mockups

See ["Footer C" ](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/469768935/preview?scrollOffset=0)

#### Acceptance Criteria:

- [ ] screenshots for desktop and mobile with the PR
- [ ] Left align and right align with the page content

**Comment by MAbdurrehman12** [comment]
@pdpinch This footer can be used for `course-v2` and `course-offline` theme but what about `www` and `fields` theme?
This might be an inconsistency if we have different footers in `course-v2` and `www`, `fields`

**Comment by MAbdurrehman12** [comment]
> What's easier?

Both options are easier since I have created a separate `footer-v2` file in `base-theme` and used it in `course-v2` for now. 
We can use it anywhere (in any theme) we like.

If we are using it in all themes then I can go on, remove the old footer and rename this to footer only (instead of footer-v2)

**Comment by pdpinch** [comment]
Can you add some screen shots to the PR for:
1. the home page (`ocw-www`) 
2. the current `ocw-course` ?

**Comment by MAbdurrehman12** [comment]
> Can you add some screen shots to the PR for:
> 
> 1. the home page (`ocw-www`)
> 2. the current `ocw-course` ?

Sure

**Comment by MAbdurrehman12** [comment]
@pdpinch You can view the footer for `www`, `course`, `course-v2` in these [netlify deployments](https://github.com/mitodl/ocw-hugo-themes/pull/868#issuecomment-1260815625).
Since footer's background was made white for `course-v2` so it's not looking quite good in other themes because they already have white background unlike course-v2.

ps: I have made a temporary commit to apply the footer to all themes, will revert it.

**Comment by MAbdurrehman12** [comment]
@pdpinch I'm reverting this commit, so you might not be able to see the compact footer in www and course themes.
However, I have taken their screenshots. You can see them [here](https://drive.google.com/drive/folders/16a-g-qDVXvbwyG_TMYSjQYDw4BdfJY2O?usp=sharing)
