### ISSUE TITLE
video player keyboard shortcuts don't work

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-themes#978]
### Steps to Reproduce

1. Visit a video page, like https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-1-the-geometry-of-linear-equations/
2. Press spacebar to play the video (it doesn't work) 
3. Click on the playback button to start the video playing 
4. Press spacebar to pause the video (it does work)
5. Press spacebar to play the video (works as long as the video has focus) 

### Expected Behavior

- The spacebar should pause and play the video, as soon as the page is loaded

### Actual Behavior

- the spacebar only works if the video has focus

### Related Issues

- There's a bunch of other [YouTube shortcuts](https://support.google.com/youtube/answer/7631406?hl=en). 
- A user asked in particular for the `f` shortcut for full screen

**Comment by ChristopherChudzicki** [comment]
Potentially related: https://github.com/mitodl/ocw-hugo-themes/issues/899

**Comment by ChristopherChudzicki** [comment]
@pdpinch Are we open to re-considering the builtin youtube controls? We would get these keyboard shortcuts for free, and there are a number of other significant advantages. See https://github.com/mitodl/hq/discussions/35

If not, we certainly can do this (and make other improvements, e.g., enable focus rings on controls bar to visualize keyboard navigation), but I wanted to check whether YouTube controls are a possible alternative.

**Comment by ChristopherChudzicki** [comment]
I was incorrect to say that "we can certainly do this" (meaning hotkeys) with VideoJS custom controls. I think there are some hard constraints around youtube sources, hotkeys, and custom controls with VideoJS. Fundamentally, the difficulty is that the YouTube video is in an iframe, the custom controls are in the parent page, each of these tries to manage hotkeys but with a bit of conflict, and attempts to reconcile the conflict are stymied by limited communication between iframes and parent frames.   

### Hotkeys and custom controls
With youtube sources and custom controls, our choices are:
- use VideoJS hotkeys when control bar is focused and no hotkeys when video is focused
- use YouTue hotkeys when video is focused and no hotkeys when

<table>
    <thead>
        <th>
            Control bar focused
        </th>
        <th>
            Video focused
        </th>
    </thead>
    <tbody>
        <tr>
            <th>enable VideoJS hotkeys only</th>
            <td>hotkeys work ✅</td>
            <td>no hotkeys ❌</td>
        </tr>
        <tr>
            <th>enable YouTube hotkeys only</th>
            <td>no hotkeys ❌</td>
            <td>hotkeys work ✅</td>
        </tr>
        <tr>
            <th>enable both YouTube <br> and VideoJS hotkeys</th>
            <td colspan="2">
                ⚠️ Hotkeys work when either element is focused, but work a little strangely. "c" can lead to double captions, and "f" for fullscreen does not always work.
            </td>
        </tr>
    </tbody>
</table>   

### YouTube Controls
Hotkeys work as expected, because the iframe owns the controls bar and the video player, so YouTube handles it.

**Comment by pdpinch** [comment]
Was this fixed by switching to the YouTube player?

**Comment by ChristopherChudzicki** [comment]
@pdpinch Yes! Closing this.
